label stm32h743-fk743m2-buildroot
  kernel /boot/zImage
  devicetree /boot/stm32h750i-art-pi.dtb
  append console=ttySTM0,115200 root=/dev/mmcblk0p1 rw rootfstype=ext2 rootwait earlyprintk consoleblank=0 ignore_loglevel
